name: Build Project

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/android-setup-composite-action

      - name: Decode google-services.json
        run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Restore release keystore.jks
        run: echo $ENCODED_STRING_R | base64 -d > ./release.keystore.jks

      - name: Restore debug keystore.jks
        run: echo $ENCODED_STRING_D | base64 -d > ./debug.keystore.jks

      - name: Assemble gradle project
        run: ./gradlew assembleFdroidDebug